# Generated by Django 5.1.2 on 2024-11-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_blog_contact_team_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.ImageField(upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='picture',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
